### ISSUE TITLE
Proposal to add guidance on ARIA versions

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/wai-intro-aria#24]
The [WAI-ARIA Overview](https://www.w3.org/WAI/standards-guidelines/aria/) page informs that there are two versions of the WAI-ARIA Recommendation, 1.0 and 1.1. However, the page is not providing the user any additional information on what version to use.

As a reader of the page, I'd expect to find a reply to the following questions:

- Is it okay to use ARIA 1.0 or is it obsolete?
- How is ARIA 1.1 different from ARIA 1.0?
- What ARIA version is better supported by assistive technologies?

**Comment by shawna-slh** [comment]
@jnurthen @spectranaut @daniel-montalvo Would you or someone in the ARIA WG be up for drafting some information about the ARIA versions, such as above?

(Also, we'll want to update "[WAI-ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/) is under development.")

**Comment by daniel-montalvo** [comment]
Hi @shawna-slh @cmuncharaz 

@jnurthen  will open a PR to address these an other issues with that ARIA intro page.

We are actually planning on updating the page to refer more prominently to the latest version once it becomes Rec. The group does not really advise to use anything older than 1.2 at this point.

**Comment by shawna-slh** [comment]
Hi @jnurthen @daniel-montalvo @spectranaut

I would like to include a pointer to [WAI-ARIA Overview](https://www.w3.org/WAI/standards-guidelines/aria/) in the announcements for ARIA 1.2 to Rec. Would you be able to do at least a quick update right away so it's accurate? You could do more polishing and refinement later.
